.github/CODEOWNERS, 배열의유사도.js, 자연수뒤집어배열로만들기.js
유사도를 찾는 문제라, 처음에는 for문을 두번 돌려야하나? 생각했는데 idx까지 겹칠필요는 없는 문제였어서
reduce를 통해 s1만을 1번 순회하면서 
s2에 해당 엘리먼트가 있으면 누적값인 acc를 올리고 아니면 acc를 올리지 않는 식으로 작성했습니다.
누적값은 0 부터 시작해야하기 때문에 초기값으로 0을 작성해주었습니다
```javascript
const solution = (s1, s2) =>
s1.reduce((acc, el) => (s2.includes(el) ? acc + 1 : acc), 0);
```
다른 풀이는 filter를 통해 s2.includes인 el만 받아낸후 길이를 계산할 수 있을 것 같습니다.
저는 reduce나 filter, map 처럼 배열 고차함수를 사용한 방법밖에 지금은 생각나지 않네요 
다른 신박한 풀이가 있다면 공유주시면 감사하겠습니다
알고리즘복잡도는 reduce한번이기에 **n**으로 예상되는데 확실한지 모르겠습니다
의견주시면 감사하겠습니다!
매개변수로 받게되는 n이 숫자이기에 바로 스프레드 문법으로 배열로 변환되지않고 타입에러를 던지게됩니다.
따라서 문자열로 변환해주어야합니다.
코드를 간결하게 작성하기위해 스프레드문법사용시 바로 템플릿리터럴을 통해 문자열로 변환해주었습니다.
그 뒤 reverse 메서드를 통해 뒤집고,
결과 값이 뒤집은 문자열 배열이기 때문에 map을 통해서 배열을 순회하며 각 요소들을 숫자로 변환해주었습니다.
```javascript
function solution(n) {
return [...`${n}`].reverse().map((el) …
```
=> [week1]이정민

.github/CODEOWNERS, 배열의 유사도.js, 자연수 뒤집어 배열로 만들기.js
filter 함수와 includes 함수를 사용하여 s1의 각 요소가 s2에 포함되어 있는지를 검사하고, 결과적으로 포함된 요소들의 배열을 생성한 다음, 그 길이를 반환합니다.
```javascript
function solution(s1, s2) {
return s1.filter((v) => s2.includes(v)).length;
}
```
```javascript
function solution(s1, s2) {
let count = 0;
for (let i = 0; i < s1.length; i++) {
for (let j = 0; j < s2.length; j++) {
if (s1[i] === s2[j]) count += 1;
}
}
return count;
}
```
무슨 함수를 써야 될지 바로 생각이 안나서 그 부분이 좀 힘들었던 것 같습니다.
확실히 함수를 사용하는 방법이 가독성도 좋고 효율성도 좋은 것 같은데 아직은 함수를 사용하는 것이 익숙하지 않은것 같습니다.
함수를 사용하는 것에 익숙해지고 기억할 수 있도록 자주 자주 사용해봐야겠다 느꼈습니다.
자연수 n을 문자열로 만든 것을 str에 넣은 뒤 str을 배열에 넣고 reverse 함수를 이용하여 뒤집은 뒤에 map 함수로 요소 각각을 숫자로 바꾸어줍니다.
reverse 함수는 배열에서만 사용이 가능하기 때문에 자연수 n을 문자열로 바꾼 str을 스프레드 문법을 사용하여 ( [...str] ) 배열로 바꾼 뒤 reverse 함수로 순서를 바꾸고, 배열안에 있는 숫자는 문자열이기 때문에 map 함수를 이용하여 요소 각각을 숫자로 바꾸어 …
=> [week1] 조형진

.github/CODEOWNERS, [week1]Liz Chung/1. 배열의 유사도.js, [week1]Liz Chung/2. 자연수 뒤집어 배열로 만들기.js
배열 s1과 s2의 원소는 알파벳 소문자만 이루어지고 중복된 원소도 갖지 않아서 filter과 includes 매소드로 s1배열에서 s2배열의 원소를 포함하는 부분을 찾아서 그 부분의 길이를 반환합니다.
```javascript
const solution = (s1, s2) => s1.filter(n => s2.includes(n)).length;
```
시간 복잡도는 TC = O(n^2)인 것 같아서 s1과 s2의 길이에 제한이 없는 경우 최적의 방법이 아닐 수도 있다고 생각합니다.
includes 매소드는 대소문자 구분할 수 없다는 부분을 유의해야 합니다. 이번 문제에서 s1과 s2의 원소는 알파벳 소문자만 이루어져서 이 방법으로 가능합니다.
n를 문자열로 바꾼 후에 배열로 바꿔서 reverse 매소드로 뒤집고 map 매소드로 숫자로 바꿔서 반환합니다. 
```javascript
const solution = n => [...n + ''].reverse().map(Number);
```
시간 복잡도를 졸이는 방법이 있을지 고민중입니다.
숫자의 순서를 처리할 때 문자열로 바꾸고 또 배열로 바꿔서 처리하는 게 더 쉬울 수도 있다는 생각입니다.
=> [week1]Liz

week3/120834_외계행성의나이.js, week3/120844_배열회전시키기.js, week3/120854_배열원소의길이.js, week3/12919_서울에서김서방찾기.js, week3/12954_x만큼간격이있는n개의숫자.js, week3/86051_없는숫자더하기.js
strlist 각 원소의 길이를 담은 배열을 return 하는 문제였는데요!
바로 map을 이용해서 각 원소의 length를 계산해서 새 배열을 return 하는 식으로 코드를 작성했습니다
```javascript
const solution = (strlist) => strlist.map((str) => str.length);
// TC O(n)  
// SC O(n)  
// n : strlist의 길이
```
그렇게 어렵지 않게 바로 map이 떠올라서 풀었던거같아요
`.length` 의 경우는 계산이 아니라 단순하게 바로 length 속성으로 접근해 길이를 받아오기 때문에 시간복잡도는 O(1)이라고 합니다! 
숫자 0 ~ 9를 받아 a ~ j 까지의 알파벳으로 변환해주는 문제였습니다!
요소가 10개짜리 배열이라 바로 사전을 만들어서 문제 풀어주었습니다
지난번 문제처럼 배열로 변환해야하는 숫자가 존재해서, 스프레드문법과 템플릿리터럴을 이용해서 변환해준뒤 
reduce로 코드 작성해주었습니다
```javascript
const dictionary = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"];
const solution = (age) => [...`${age}`].reduce((acc, el) => acc + dictionary[el], "");
// TC O(n)  2n -> n
// SC O(n)  
// n : age의 길이
```
(풀이 중 힘든 점이 있었다면 왜 힘들었고 어떻게 해결했는지, 아니면 이외의 좋을 것 같은 다른 풀이법이 있다면 같이 …
=> [week3] 이정민

n의 배수 고르기.js, x만큼 간격이 있는 n개의 숫자.js, 가운데 글자 가져오기.js, 대문자와 소문자.js, 두 정수 사이의 합.js, 배열 원소의 길이.js, 배열 회전시키기.js, 서울에서 김서방 찾기.js, 암호 해독.js, 없는 숫자 더하기.js, 외계행성의 나이.js, 조건에 맞게 수열 변환하기 3.js
배열 안에 있는 문자열의 길이를 반환하면 되기 때문에 map 함수를 이용하여 문자열 각각의 길이(length)를 반환하도록 했습니다.
```javascript
const solution = strlist => strlist.map(e => e.length);
```
```javascript
const solution = strlist => {
let res = [];
for (let i = 0; i < strlist.length; i++) {
res.push(strlist[i].length);
}
return res;
}
```
map을 써야겠다 바로 생각이나서 어렵지 않게 푼 문제 같습니다. 
a ~ j 까지 알파벳을 alpa라는 문자열에 넣고 age를 문자열로 바꾼 것을 스프레드문법을 이용하여 배열로 만든 뒤 
map 함수로 순회하면서 각 원소를 숫자 타입으로 변환(+e)한 후 해당 숫자에 맞는 alpa의 문자로 변환되도록 했습니다.
```javascript
function solution(age) {
let alpa = "abcdefghij";
return [...(age + "")].map((e) => alpa[+e]).join("");
}
```
변환해야되는게 좀 많아서 까다로웠던거 빼고 많이 어려웠던 문제는 아닌것 같았습니다.
direction이 right면 마지막 요소가 첫번째 요소가 되고 direction이 left면 첫번째 요소가 마지막 요소가 되도록 slice를 이용해서 풀어봤습니다.
```javascript
function solution(numbers, direction) { …
```
=> [Week3]조형진

1차 비밀지도.js, 배열의 원소 삭제하기.js, 수박수박수박수박수박수.js, 주사위의 개수.js, 콜라츠 수열 만들기.js, 핸드폰 번호 가리기.js
box 배열의 각 요소를 n으로 나눈 값의 정수 부분을 res 값에 곱하고 res를 반환하도록 풀었습니다.
```javascript
function solution(box, n) {
let res = 1;
for (let i = 0; i < box.length; i++) {
res *= Math.trunc(box[i] / n);
}
return res;
}
```
```
function solution(box, n) {
return box.reduce((acc, el) => acc * Math.trunc(el / n), 1);
}
```
처음으로 reduce를 이용해서 풀어봤는데 확실히 for문으로 먼저 풀어보니까 reduce로 쉽게 풀 수 있었던 것 같아요 !
filter와 includes를 이용해서 delete_list를 포함하지 않는 것만 반환하도록 풀었습니다.
```javascript
function solution(arr, delete_list) {
return arr.filter((el) => !delete_list.includes(el));
}
```
while과 if else를 이용해 num이 1이 아닐때까지 num이 짝수면 num / 2 한 것을 push하고 num이 홀수면 3 * num + 1 한 것을 push해서 res를 반환하도록 풀었습니다.
```javascript
function solution(n) {
let res = [];
let num = n;
while (num !== 1) {
res.push(num);
if (num % 2 === 0) {
num /= 2;
} else { …
```
=> [week4] 조형진

flag에 따라 다른 값 반환하기.js, qr code.js, 수박수박수박수박수박수.js, 실패율.js, 컨트롤 제트.js, 폰켓몬.js
flag가 true면 a + b , false면 a - b를 반환하도록 풀었습니다.
```javascript
function solution(a, b, flag) {
return flag ? a + b : a - b;
}
```
true false 문제라서 `return flag === true ? a + b : a - b;` 이렇게 쓰지 않아도 될 것 같습니다.
pop과 push를 이용하여 arr[i] === "Z" 라면 pop을 하고 아니라면 push를 하여 res 배열에 있는 값들을 더한 값을 반환하도록 했습니다. 
```javascript
function solution(s) {
let arr = s.split(" ");
let res = [];
for (let i = 0; i < arr.length; i++) {
if (arr[i] === "Z") {
res.pop();
} else {
res.push(+arr[i]);
}
}
return res.reduce((acc, cur) => acc + cur, 0);
}
```
스택 문제였던 것 같은데 많이 봐왔던 문제가 아니여서 조금 오래 생각했던 것 같습니다..
인덱스 값을  q로 나눈 나머지가 r인 값들만 반환하도록 했습니다.
```javascript
function solution(q, r, code) {
let res = "";
for (let i = 0; i < code.length; i++) {
if (i % q === r) res += code[i];
}
return res;
}
```
```javascript
function …
```
=> [week5] 조형진

week5/flag에 따라 다른 값 반환하기.js, week5/qr code.js, week5/실패율.js, week5/컨트롤 제트.js, week5/폰켓몬.js
삼항연산자를 통해 `flag`의 값은 true이면 `a + b`를 반환하고 `false`이면 `a - b`를 반환합니다.
```javascript
const solution = (a, b, flag) => flag === true? a + b : a - b;
// TC = O(1); SC = O(1);
```
```javascript
const solution = (a, b, flag) => flag? a + b : a - b;
```
`flag === true?`와 같이 판단해야 되는 값은 불리언이면 `flag?`로 생략할 수 있습니다.
`.split()`를 사용해서 문자열 s의 공백을 기준으로 새로운 배열을 만듭니다. 반환할 결과값 `res`는 0로 초기화하고, 마지막에 연산한 값 `lastValidNumber`도 0로 초기화합니다. 그렇고 나서 for문을 돌리고 for문 안에 if문을 사용합니다. 배열 arr의 원소는 `'Z'`이면 그전에 더한 값을 빼고, `lastValidNumber`를 다시 0로 초기화합니다. 나머지 경우에는 arr의 원소들을 더하고, `lastValidNumber`의 값은 연산하고 있는 값으로 지정합니다.
```javascript
const solution = (s) => {
const arr = s.split(' ');
let res = 0;
let lastValidNumber = 0;
for (const item of arr) {
if (item === 'Z') {
res -= lastValidNumber;
lastValidNumber = 0;
} else {
res += …
```
=> [week5] Liz

week6/120837_개미군단.js, week6/120839_가위바위보.js, week6/12935_제일작은수제거하기.js, week6/181893_배열조각하기.js, week6/77884_약수의개수와덧셈.js
query배열의 인덱스의 짝홀 여부에 따라 arr를 앞을 자르거나 뒤를 잘라서 return 해주는 문제였습니다!!
문제 해석이 조금 어려웠어서 ㅜ.ㅜ 은근히 오래걸렸던거같아요
결론적으로 짝홀따지는건 query배열의 인덱스였다는 것만 알면 꽤 괜찮게 풀렸던거 같습니다!
또 arr 배열이 계속 변화하고 그 변화한 배열에 다시 앞 뒤를 자르거나 하기 때문에, 
초기값을 arr배열로 주고 acc에 변화하는 값을 저장해주면서 코드를 작성했습니다!
```javascript
const solution = (arr, query) =>
query.reduce(
(acc, el, idx) =>
idx % 2 === 0 ? (acc = acc.slice(0, el + 1)) : (acc = acc.slice(el)),
arr
);
console.log(solution([10, 8], [1]));
```
알고리즘 부분에 작성했습니다! 🫡
이전에 풀어봤던 기억이 나서 빠르게 풀었던거같아요!!!
가장 큰 체력을 가진 개미부터 마리수를 계산하고,
개미 . 수 * 개미체력 을 총 hp에서 빼서 남은 체력에서 다시 그 다음으로 체력이 큰 개미의 수를 계산하는 방식으로 코드를 작성했습니다..
!!!!
```javascript
const solution = (hp) => {
const generalAntCount = Math.trunc(hp / 5);
const soldierAntCount = Math.trunc((hp - generalAntCount * 5) / 3);
const workerAntCount = hp - …
```
=> [week6] 이정민

가위바위보.js, 개미 군단.js, 배열 조각하기.js, 약수의 개수와 덧셈.js, 제일 작은 수 제거하기.js
for문과 slice를 이용하여 인덱스가 짝수인 경우 query[i]번 인덱스 뒷부분을 잘라서 버리고 인덱스가 홀수인 경우 query[i]번 인덱스 앞부분을 잘라서 버린 res 배열을 반환하도록 풀었습니다.
```javascript
function solution(arr, query) {
let res = [...arr];
for (let i = 0; i < query.length; i++) {
i % 2 === 0 ? res = res.slice(0, query[i] + 1) : res = res.slice(query[i]);
}
return res;
}
function solution(arr, query) {
let res = [...arr];
query.forEach((q, i) => {
res = i % 2 === 0 ? res.slice(0, q + 1) : res.slice(q);
});
return res;
}
```
for문과 forEach문 각각 이용해서 풀어봤는데요, forEach문이 좀 더 나은 풀이 같습니다.
문제를 이해하는데 꽤 오래 걸린 문제였던 것 같아요.. 
그리고 slice를 사용하는 건 아직도 미숙한 것 같아요 ㅠㅠ
사냥감의 체력에 딱 맞는 최소한의 병력을 구성해야 되기 때문에 처음에는 hp를 5로 나눈 정수의 값을 더하고 
hp를 5로 나눈 나머지를 3으로 나눈 정수의 값을 더하고 hp를 5로 나눈 나머지를 다시 3으로 나눈 값을 더해서 필요한 최소한의 개미 수를 반환하도록 했습니다.
```javascript
function solution(hp) {
return …
```
=> [week6] 조형진

날짜 비교하기.js, 로그인 성공.js, 음양 더하기.js, 캐릭터의 좌표.js, 커피 심부름.js
최댓값을 설정하고 right, left, up, down 에 따라 a, b 값을 연산하여 배열로 반환하도록 풀었습니다.
```javascript
function solution(keyinput, board) {
let a = 0;
let b = 0;
let maxA = Math.trunc(board[0] / 2);
let maxB = Math.trunc(board[1] / 2);
for (let i = 0; i < keyinput.length; i++) {
if (keyinput[i] === "right" && a + 1 <= maxA) a++;
if (keyinput[i] === "left" && a - 1 >= -maxA) a--;
if (keyinput[i] === "up" && b + 1 <= maxB) b++;
if (keyinput[i] === "down" && b - 1 >= -maxB) b--;
}
return [a, b];
}
```
최댓값을 넘지 않도록 조건을 만드는 부분이 생각하는데 오래 걸렸던 것 같습니다.
저에게 좀 어려웠던 문제였는데 더 좋은 풀이가 있는지, 다른 분들은 어떻게 푸셨는지 궁금합니다 !
아이디와 비밀번호가 모두 일치하는 것이 있으면 "login",  아이디는 일치하지만 비밀번호가 다르면 “wrong pw”, 모두 일치하는 것이 없다면 "fail"을 반환하도록 풀었습니다.
```javascript
function solution(id_pw, db) {
for (let i = 0; i < db.length; i++) {
if (db[i][0] === id_pw[0] && …
```
=> [week7] 조형진

week6/120837_개미군단.js, week6/120839_가위바위보.js, week6/12935_제일작은수제거하기.js, week6/181893_배열조각하기.js, week6/77884_약수의개수와덧셈.js, week7/120861_캐릭터의좌표.js, week7/120883_로그인성공.js, week7/181837_커피심부름.js, week7/181838_날짜비교하기.js, week7/76501_음양더하기.js
키보드에 따른 값을 테이블로 표시하고, 
maxX, maxY값을 구해놓았습니다.
내부 구현은 식에 써놓을게요!
```javascript
function solution(keyinput, board) {
const table = {
up: [0, 1],
down: [0, -1],
left: [-1, 0],
right: [1, 0],
};
const [maxX, maxY] = [Math.floor(board[0] / 2), Math.floor(board[1] / 2)];
const position = keyinput.reduce(
(acc, key) => {
const [dx, dy] = table[key]; // 이동할 위치 값을 뽑아놨습니다
return [
// 이동한 위치( acc + d )가 max값보다 작다면, 이동하게 만들고 아니라면 이동하지 않도록 만들었습니다
Math.abs(acc[0] + dx) <= maxX ? acc[0] + dx : acc[0],   
Math.abs(acc[1] + dy) <= maxY ? acc[1] + dy : acc[1],
];
},
[0, 0]
);
return position;
}
```
처음에는 다 더한다음에 max값과 비교하려고 했는데요! 
생각해보니까 끝까지 가서 막혔다가, 반대로 가게되는 경우가 있을 수 있을 거 같아서 이동할 때마다 max값과 비교해주었습니다
8번케이스에 걸려서 다른문제보다 쬐끔더 오래걸렸네요 ㅜ.ㅜ
리즈님 문제 골라오시는 솜씨가.. 너무 좋아요
너무 새로워서 시간없이 급하게 풀었는데도 너무 재미있게 풀었습니다 ㅜ.ㅜ 😍
유저의 id와 …
=> [week7] 이정민

week8/체육복.js, week8/피로도.js
전체학생 n 과 체육복 잃어버린 학생목록 lost, 여분체육복을 가지고있는(체육복2개씩가지고있는) 친구들의 목록 reserve를 받아서
체육수업에 참가할 수 있는 학생의 수를 구하는 문제였습니다 !!
풀이설명은 코드에 주석으로 적어놨습니다!!
```javascript
function solution(n, lost, reserve) {
// 여분의 체육복을 가져온 학생 중 도난당한 학생을 제외한 리스트
const realReserve = reserve.filter((el) => !lost.includes(el));
// 도난당한 학생 중 여분의 체육복을 가져온 학생을 제외한 리스트
const realLost = lost
.filter((el) => !reserve.includes(el))
.sort((a, b) => a - b);
// 수업을 들을 수 있는 학생 수 (전체 학생 수 - 도난당한 학생 수)
let number = n - realLost.length;
// 여분의 체육복을 가지고 있는 학생들의 Set , has랑 delete 메서드를 쓰기 위해서 사용했습니다
const reserveSet = new Set(realReserve);
realLost.forEach((el) => {
if (reserveSet.has(el - 1)) {
number++;
reserveSet.delete(el - 1);
} else if (reserveSet.has(el + 1)) {
number++;
reserveSet.delete(el + 1);
}
});
return number;
}
```
아래 if문을 사용할때 …
=> [week8] 이정민

체육복.js
전체 학생의 수 n, 체육복을 도난당한 학생들의 번호가 담긴 배열 lost, 여벌의 체육복을 가져온 학생들의 번호가 담긴 배열 reserve가 주어질 때 체육수업을 들을 수 있는 학생의 최댓값을 반환하는 문제였습니다.
```javascript
function solution(n, lost, reserve) {
let lostStudent = lost.filter((el) => !reserve.includes(el)).sort();
let reserveStudent = reserve.filter((el) => !lost.includes(el)).sort();
for (let i = 0; i < reserveStudent.length; i++) {
if (lostStudent.includes(reserveStudent[i] - 1))
lostStudent = lostStudent.filter((el) => el !== reserveStudent[i] - 1);
else if (lostStudent.includes(reserveStudent[i] + 1))
lostStudent = lostStudent.filter((el) => el !== reserveStudent[i] + 1);
}
return n - lostStudent.length;
}
```
저에겐 너무 어려웠던 문제여서 다른 분들 풀이 참고해서 풀었습니다..ㅠㅠ
바로 앞 번호의 학생이나 바로 뒷 번호의 학생에게만 체육복을 빌려줄 수 있는 조건을 만족하면서 어떤식으로 문제를 풀어야 할지 생각이 잘 안났던 것 같습니다 .
풀이를 계속 보다 보니 이해가 …
=> [week8] 조형진

로또의 최고 순위와 최저 순위.js, 부족한 금액 계산하기.js
알아볼 수 없는 번호를 0으로 표기하고 구매한 로또 번호 lottos와 로또 당첨 번호 win_nums가 주어졌을 때,  당첨 가능한 최고 순위와 최저 순위를 반환하는 문제였습니다.
```javascript
function solution(lottos, win_nums) {
let rank = [6, 6, 5, 4, 3, 2, 1]; 
// 0, 1개 번호가 일치할 때 6등, 2개 번호가 일치할 때 5등, 3개 번호가 일치할 때 4등,
// 4개 번호가 일치할 때 3등, 3개 번호가 일치할 때 2등, 6개 번호가 일치할 때 1등
let min = lottos.filter((el) => win_nums.includes(el)).length;
// 당첨 가능한 최저 순위일때의 일치한 번호 개수
let max = min + lottos.filter((el) => el === 0).length;
// 당첨 가능한 최고 순위일때의 일치한 번호 개수 (당첨 가능한 최저 순위일때의 일치한 번호 개수 + 0의 개수)
return [rank[max], rank[min]];
}
```
당첨 가능한 최저, 최고 순위일때의 일치한 번호 개수를 구하는 방법은 알았으나, 이것을 어떻게 등수로 바꿔야 할까 고민하다가 다른 분들의 풀이를 보고 ```let rank = [6, 6, 5, 4, 3, 2, 1]; ``` 이렇게 풀이를 했습니다.
놀이기구의 원래 이용료는 price원 인데, 놀이기구를 N 번 째 이용한다면 원래 이용료의 N배를 받을때, 놀이기구를 count번 타게 되면 현재 자신이 가지고 있는 금액에서 얼마가 모자라는지를 …
=> [week9] 조형진

week9/로또의 최고 순위와 최저 순위.js, week9/부족한 금액 계산하기.js
코드 안에 주석으로 작성했습니다.
```javascript
function solution(lottos, win_nums) {
const ranking = {
6: 1,
5: 2,
4: 3,
3: 4,
2: 5,
1: 6,
0: 6
};
// 로또 순위를 결정하기 위한 객체
const knownMatches = lottos.filter(num => win_nums.includes(num)).length;
// 당첨 번호와 일치하는 번호의 개수를 센다
const zeroCount = lottos.filter(num => num === 0).length;
// 알아볼 수 없는 번호(0)의 개수를 센다
const maxMatches = knownMatches + zeroCount;
// 최고 순위는 맞춘 번호 개수에 0의 개수를 더한 값으로 계산
return [ranking[maxMatches], ranking[knownMatches]];
}
```
가우스 공식으로 풀었습니다.
```javascript
function solution(price, money, count) {
const res = price * (count + 1) * (count / 2) - money;
return res > 0? res : 0;
}
```
=> [week9] Liz

week10/12982_예산.js, week10/131705_삼총사.js
지난주에 풀이했던 reduce에 배열을 넣는 방법으로 풀이해봤습니다! 
```javascript
function solution(d, budget) {
// 낮은 금액순으로 정렬
const sortedBudget = d.sort((a, b) => a - b);
// total에 [합산값, count]를 넣어서 합산값이 budget을 넘지 않을때만 total, count를 업데이트
const result = sortedBudget.reduce(
([total, count], el) =>
total + el <= budget ? [el + total, count + 1] : [total, count],
[0, 0]
);
// 지원 가능한 부서의 숫자 return
return result[1];
}
```
forEach와 for문을 이용해서도 풀어보았습니다~!
```javascript
function solution(d, budget) {
const sortedBudget = d.sort((a, b) => a - b);
let total = 0;
let count = 0;
sortedBudget.forEach((el) => {
if (total + el <= budget) {
total = total + el;
count = count + 1;
}
});
return count;
}
```
```javascript
function solution(d, budget) {
const sortedBudget = d.sort((a, b) => a - b);
let total = 0;
let count = 0;
for …
```
=> [week10] 이정민

삼총사.js, 예산.js
부서별로 신청한 금액이 들어있는 d와 예산 budget이 주어질 때 최대 몇 개의 부서에 물품을 지원할 수 있는지 반환하는 문제였습니다.
```javascript
function solution(d, budget) {
d.sort((a, b) => a - b); 
let res = 0;
for (let i = 0; i < d.length; i++) {
if (d[i] > budget) break;  
budget -= d[i];   
res += 1;
}
return res;
}
```
정수 배열 number가 매개변수로 주어질 때 삼총사를 만들 수 있는 방법 ( 3개의 수를 더했을 때 0이 되는 ) 의 수를 반환하는 문제였습니다. 
```javascript
function solution(number) {
let res = 0;
for (let i = 0; i < number.length; i++) {
for (let j = i + 1; j < number.length; j++) {
for (let k = j + 1; k < number.length; k++) {
if (number[i] + number[j] + number[k] === 0) res += 1;
}
}
}
return res;
}
```
```javascript
function solution(number) {
let result = 0;
const combination = (current, start) => {
if (current.length === 3) {
result += current.reduce((acc, cur) => acc + …
```
=> [week10] 조형진

week10/삼총사.js, week10/예산.js
(코드 안에 주석으로 설명했습니다)
```javascript
function solution(d, budget) {
d.sort((a, b) => a - b);
// 부서별로 신청한 금액을 오름차순으로 정렬합니다.
let res = 0;
// 물품을 구매하는데 사용한 총 금액을 저장하는 변수입니다.
let count = 0;
// 지원해줄 수 있는 부서의 수를 세는 변수입니다.
for (const v of d) {
res += v;
if (res <= budget) count ++;
}
// 각 부서의 신청 금액을 하나씩 확인합니다.
// 예산을 초과하지 않으면 부서 수를 증가시킵니다.
return count;
}
```
```javascript
function solution(d, budget) {
return d.sort((a, b) => a - b).reduce((count, price) => {
return count + ((budget -= price) >= 0);
}, 0);
}
```
(풀면서 느낀점 이외에도 기억할 점이나 같이 논의하고 싶은 부분 등이 있다면 자유롭게 적어주세요)
(코드 안에 주석으로 설명했습니다)
```javascript
function solution(number) {
let count = 0;
function findCombination(start, depth, sum) {
if (depth === 3) {
if (sum === 0) {
count++;
}
return;
}
for (let i = start; i < number.length; i++) { …
```
=> [week10] Liz

week11/다트 게임.js, week11/푸드 파이트 대회.js
코드 안에 주석으로 작성했습니다.
```javascript
function solution(food) {
// food 배열의 각 요소를 반복하여 문자열로 변환한 후, 절반의 개수만큼 반복된 문자열을 만든다.
const foodInUse = food.map((el, i) => String(i).repeat(Math.trunc(el / 2))).join('');
// foodInUse 문자열과 '0'을 중간에 넣고, foodInUse 문자열의 역순을 붙여서 최종 문자열을 반환한다.
return foodInUse + '0' + [...foodInUse].reverse().join('');
}
```
```javascript
function solution(food) {
// 빈 문자열을 초기화하여 foodInUse 변수에 저장
let foodInUse = '';
// food 배열의 각 요소에 대해 반복
food.forEach((el, i) => {
// 인덱스를 문자열로 변환한 것을 el의 절반(내림)만큼 반복하여 foodInUse에 추가
foodInUse += String(i).repeat(Math.floor(el / 2));
});
// foodInUse 문자열에 '0'을 추가하고, foodInUse를 뒤집어 다시 추가하여 반환
return foodInUse + '0' + [...foodInUse].reverse().join('');
}
```
map와 forEach 두 가지 메소드로 풀어봤는데, 크게 차이가 없을 것 같지만 map로 푸는 게 더 간단해 보인 것 같습니다. 다른 방법도 있는지 궁금합니다. …
=> [week11] Liz

week12/성격 유형 검사하기.js, week12/추억 점수.js
- `scoreMap` 객체를 사용하여 각 성격 유형별 점수를 저장합니다. 초기 점수는 모두 0으로 설정합니다. 
- `choicePoints` 객체를 사용하여 각 선택지에 해당하는 점수를 정의합니다.
- `.forEach()`로 `survey` 배열과 `choices` 배열을 순회하며 각 질문에 대한 선택지를 확인합니다. 각 질문에 대해 선택지가 4 미만이면 `disagreeType` (비동의 유형)에 해당하는 점수를 `scoreMap`에 추가합니다. 선택지가 4보다 크면 `agreeType` (동의 유형)에 해당하는 점수를 `scoreMap`에 추가합니다.
- 각 성격 지표(RT, CF, JM, AN)에서 점수가 높은 유형을 선택합니다. 점수가 같은 경우, 사전순으로 빠른 유형을 선택합니다.
```javascript
function solution(survey, choices) {
const scoreMap = {
R: 0, T: 0,
C: 0, F: 0,
J: 0, M: 0,
A: 0, N: 0
};
const choicePoints = {
1: 3, 
2: 2, 
3: 1, 
4: 0, 
5: 1, 
6: 2, 
7: 3
};
survey.forEach((typePair, i) => {
const [disagreeType, agreeType] = typePair;
const choice = choices[i];
if (choice < 4) scoreMap[disagreeType] += choicePoints[choice];
else if (choice > 4) scoreMap[agreeType] += …
```
=> [week12] Liz

week12/118666_성격유형_검사하기.js, week12/176963_추억_점수.js
- 초기화 단계
각 성격 유형의 점수를 저장할 객체 types를 초기화합니다. types 객체는 각각의 키를 가지며, 초기값은 모두 0입니다.
- 점수 계산
survey와 choices 배열을 동시에 순회하면서 각 설문조사 항목에 대해 점수를 계산합니다. 각 설문조사 항목(pair)은 두 가지 성격 유형(left, right)으로 이루어져 있습니다. 선택지(choices[index])가 4보다 작으면 left 유형에 점수를 추가하고, 4보다 크면 right 유형에 점수를 추가합니다. 점수는 Math.abs(choices[index] - 4)로 계산되며, 해당 값은 선택지와 4 차이의 절대값입니다.
- 결과 계산
네 쌍의 성격 유형("RT", "CF", "JM", "AN")을 순회 하면서, 각 쌍에서 점수를 비교합니다. 각 쌍에서 더 높은 점수를 가진 유형을 선택하여 결과 문자열에 추가합니다.
```javascript
function solution(survey, choices) {
const types = { R: 0, T: 0, C: 0, F: 0, J: 0, M: 0, A: 0, N: 0 };
survey.forEach((pair, index) => {
const [left, right] = pair;
types[choices[index] < 4 ? left : right] += Math.abs(choices[index] - 4);
});
return ['RT', 'CF', 'JM', 'AN'].map(pair => 
types[pair[0]] >= types[pair[1]] ? pair[0] : …
```
=> [week12] 김고성

week13/가장 많이 받은 선물.js, week13/예산.js, week13/체육복.js
- 데이터 구조 초기화: 모든 사람의 Given(준 선물), Received(받은 선물), giftPoints(선물 지수), nextMonthGifts(다음 달 받을 선물) 값을 0으로 초기화합니다.
- 주고받은 선물 개수 카운트: gifts 배열을 순회하며 각 선물을 준 사람과 받은 사람을 분리하여 Given과 Received 값을 증가시킵니다.
- 각 사람의 선물 지수 계산: 각 사람의 선물 지수는 받은 선물 개수에서 준 선물 개수를 뺀 값으로 계산합니다.
- 다음 달에 누가 누구에게 선물을 줄지 결정: 한 사람이 다른 사람에게 준 선물과 받은 선물의 개수를 비교하여 nextMonthGifts 값을 업데이트합니다. 선물 개수가 동일하면 선물 지수를 비교합니다.
- 가장 많은 선물을 받는 친구가 받을 선물의 수 찾기: nextMonthGifts 값을 순회하여 가장 많은 선물을 받을 친구가 받을 선물의 수를 찾습니다.
```javascript
function solution(friends, gifts) {
const Given = {};
const Received = {};
const giftPoints = {};
const nextMonthGifts = {};
// 데이터 구조 초기화
friends.forEach(friend => {
Given[friend] = 0;
Received[friend] = 0;
giftPoints[friend] = 0;
nextMonthGifts[friend] = 0;
});
// 주고받은 선물 개수 카운트
gifts.forEach(gift => {
const [giver, …
```
=> [Week13] Liz

week13/.github/CODEOWNERS, week13/12982_예산.cpp, week13/258712_가장 많이 받은 선물.cpp, week13/42862_체육복.cpp, week13/README.md
```cpp
/* 아이디어
개념: 2차원 배열로 행렬 이해, 상삼각(하삼각) 행렬
로직:
A. 선물 기록 유무에 관해 분기
1. 선물을 주고 받았다면, 과거 내역 비교 후 산정
1-1. 선물을 더 줬다면, 준 사람이 받을 선물 증가
1-2. 선물을 덜 줬다면, 받은 사람이 받을 선물 증가
2. 선물을 주고 받지 않았다면, 선물 지수 비교 후 산정
B. 선물 개수 최대값 산정 및 반환
*/
/* Algorithm getMostGiftsNextMonth(F, G)
Input : String Array F, String Array G
Output: The number of gifts a friend will receive the most gifts in the next month
R ← Matrix of F.size() × F.size()
for giver ← 0 to F.size() - 1 do
for recipient ← 0 to F.size() - 1 do
if giver = recipient then
continue
for all history ∈ G
if F[giver] = history.split()[0] and F[recipient] = history.split()[1] then
R[giver][recipient] ← R[giver][recipient] + 1
M ← Map, consists of a friend as the Key and gifts for next month as the Value
for giver ← 0 to F.size() - 1 do
for recipient ← giver to …
```
=> [week13]백승헌

week14/숫자 문자열과 영단어.js, week14/크레인 인형뽑기 게임.js, week14/폰켓몬.js, week15/대충 만든 자판.js, week15/덧칠하기.js, week15/실패율.js
- 유일한 종류의 폰켓몬을 찾기 위해 Set 사용합니다
- 최대 선택 가능한 폰켓몬의 종류 수 계산합니다: nums.length / 2는 N/2 마리를 선택할 수 있는 최대 수를 나타내고, set.size는 중복을 제거한 폰켓몬 종류의 수를 나타냅니다. 최대 선택 가능한 종류 수는 두 값 중 작은 값이 됩니다. 그 이유는 선택할 수 있는 폰켓몬의 수는 최대 N/2입니다. 그러나 중복을 제거한 종류의 수가 N/2보다 적으면, 선택 가능한 종류 수는 중복을 제거한 종류의 수가 됩니다. 따라서 nums.length / 2 < set.size가 참이면, nums.length / 2를 반환하고, 그렇지 않으면 set.size를 반환합니다.
```javascript
const solution = (nums) => {
const set = new Set(nums);
return nums.length / 2 < set.size ? nums.length / 2 : set.size;
};
```
질문의 설명 자체가 길지만, 폰켓몬 종류의 개수를 반환하는 거여서 바로 `.set()`가 떠올렸습니다. `.set()`로 폰켓몬 종류의 충 개수를 찾아낸 후에, 선택할 수 있는 최대 개수 N/2와 비교하면 바로 풀 수 있었습니다.
긴 문제에서 핵심 로직만 파악하면 해결방법이 아주 간단할 수도 있습니다.
초기화: result 객체는 두 가지를 저장합니다: basket (바구니에 담긴 인형 리스트)와 count (터뜨린 인형의 수).
board 배열은 격자의 상태를 가로로 나타내지만, 배열 moves에서는 column의 번호로 새로 …
=> [week14] Liz

week16/12906_같은숫자는싫어.js, week16/42748_K번째수.js, week16/72410_신규아이디추천.js
간단하게 index를 이용해 뒤에 같은 값이 오지 않으면 해당 요소를 담는 방식으로 작성했습니다
reduce를 이용해서 풀었는데 풀고보니까 filter로도 충분히 가능해서 변경해보았습니다!
```javascript
function solution(arr) {
return arr.reduce((acc, el, idx) => {
if (el !== arr[idx + 1]) acc.push(el);
return acc;
}, []);
}
```
```javascript
function solution(arr) {
return arr.filter((el, idx) => el !== arr[idx + 1]);
}
```
`acc.push(el);` 시 return값은 배열이 아닌 배열의 길이를 반환한다 ..!! 
맨날까먹어서 수정하게 되는 부분 같아요
제가 기억하고싶어서 한번 더 적어놓습니다 
문제에서 요구하는대로 풀이했습니다
문제를 그대로 따라가면 되는 문제라 풀이를 따로 생각하지 않고 바로 작성했습니다... 🧐
```javascript
function solution(array, commands) {
return commands.map(
([i, j, k]) => array.slice(i - 1, j).sort((a, b) => a - b)[k - 1]
);
}
```
2번 문제와 동일하게 문제를 따라가면서 풀이했습니다
주로 정규표현식을 이용해서 풀이했습니다!!
```javascript
function solution(new_id) {
const id_1 = new_id.toLowerCase();
const …
```
=> [week16] 이정민

pull_request_template.md, week17/개인정보수집유효기간.js, week17/기사단원의무기.js, week17/문자열내마음대로생성하기.js
(왜 이렇게 코드를 작성했는지 이유를 적어주세요)
```javascript
function solution(strings, n) {
return strings.sort((s1, s2) => s1[n] === s2[n] ?
s1.localeCompare(s2) : s1[n].localeCompare(s2[n]));
}
```
(풀이 중 힘든 점이 있었다면 왜 힘들었고 어떻게 해결했는지, 아니면 이외의 좋을 것 같은 다른 풀이법이 있다면 같이 작성해주세요)
(풀면서 느낀점 이외에도 기억할 점이나 같이 논의하고 싶은 부분 등이 있다면 자유롭게 적어주세요)
(왜 이렇게 코드를 작성했는지 이유를 적어주세요)
1. number 크기의 배열 cnt를 0으로 초기화합니다. 이 배열은 각 숫자의 약수 개수를 저장합니다.
2. 각 숫자 i에 대해 1부터 √(i+1)까지 반복하여 약수의 개수를 계산합니다.
•	(i+1) % k === 0인 경우, k가 i+1의 약수임을 의미합니다.
•	k가 i+1의 제곱근인 경우 약수 개수를 1 증가시키고, 그렇지 않은 경우 약수 개수를 2 증가시킵니다.
•	이렇게 계산한 약수 개수를 배열 cnt의 i번째 요소에 저장합니다.
3. 배열 cnt의 각 요소에 대해 limit을 초과하는 경우 해당 요소를 power로 대체합니다.
4. 배열 cnt의 모든 요소의 합을 계산하여 result에 저장합니다.
```javascript
function solution(number, limit, power) {
// 각 숫자의 약수 개수를 저장할 배열
let cnt = new …
```
=> [week17] 조천산

week18/172928_공원산책.js, week18/250137_붕대감기.js, week18/42840_모의고사.js
각 학생의 패턴을 정의해주고,
점수를 계산해주는 함수를 따로 작성해서 풀이해줬습니다 !! 
highestScore를 계산된 점수배열에서 가져와서 스코어가 최고점수랑 동일한 학생을 return 해주었습니다
```javascript
const PATTERNS = [
[1, 2, 3, 4, 5],
[2, 1, 2, 3, 2, 4, 2, 5],
[3, 3, 1, 1, 2, 2, 4, 4, 5, 5],
];
const calculationScores = (answers, pattern) => {
let count = 0;
for (let i = 0; i < answers.length; i++) {
const patternIndex = i % pattern.length;
if (answers[i] === pattern[patternIndex]) count++;
}
return count;
};
const solution = (answers) => {
const answer = [];
const scores = PATTERNS.reduce((acc, pattern) => {
acc.push(calculationScores(answers, pattern));
return acc;
}, []);
const highestScore = Math.max(...scores);
scores.forEach((score, index) => {
if (highestScore === score) answer.push(index + 1);
});
return answer;
};
const solution2 = (answers) => { …
```
=> [week18] 이정민

week19/17681_비밀지도.js, week19/17682_다트게임.js, week19/77484_로또의최고순위와최저순위.js
설계와 다른 풀이 오늘안으로 추가해놓겠습니다!
```javascript
const solution = (n, arr1, arr2) => {
const calcArr = arr1.map(
(el, idx) => +el.toString(2) + +arr2[idx].toString(2) + ""
);
const replacedString = (str) => str.replace(/0/g, " ").replace(/[1-9]/g, "#");
return calcArr.map((el) =>
el.length < n
? replacedString("0".repeat(n - el.length) + el)
: replacedString(el)
);
};
```
(풀이 중 힘든 점이 있었다면 왜 힘들었고 어떻게 해결했는지, 아니면 이외의 좋을 것 같은 다른 풀이법이 있다면 같이 작성해주세요)
(풀면서 느낀점 이외에도 기억할 점이나 같이 논의하고 싶은 부분 등이 있다면 자유롭게 적어주세요)
(왜 이렇게 코드를 작성했는지 이유를 적어주세요)
```javascript
function solution(dartResult) {
const optionTable = {
"*": (n) => +n * 2,
"#": (n) => +n * -1,
};
const bonusTable = {
S: (n) => +n,
D: (n) => Math.pow(+n, 2),
T: (n) => Math.pow(+n, 3),
};
const splitResult = dartResult.split(/(?=\d)/);
const resultArray = …
```
=> [week19] 이정민

week21/1844_게임맵최단거리.js, week21/42583_다리를지나는트럭.js, week21/42626_더맵게.js, week21/42842_카펫.js, week21/43165_타겟넘버.js
정수 배열이 주어졌을때 (numbers)
이를 순서대로 더하거나 빼서 target 넘버가 되는 경우의 수를 return하는 문제였습니다.
전체 조합을 찾는 경우였기 때문에 DFS로 설계하였습니다!
```javascript
function solution(numbers, target) {
let count = 0;
function dfs(depth, currentSum) {
// 현재 depth가 마지막일때 최종 검사
if (depth === numbers.length) {
// target과 같으면 count ++, 아니면 return
if (currentSum === target) {
count++;
}
return;
}
// 다음 단계로 진행
dfs(depth + 1, currentSum + numbers[depth]);
dfs(depth + 1, currentSum - numbers[depth]);
}
dfs(0, 0);
return count;
}
```
더하거나 빼는 경우를 생각해야해서 어떻게 짜야할지 고민이 조금있었는데
단순하게 각 경우를 재귀로 호출해주면 되었습니다
예전에 그래프 자료구조를 공부하지 않고 탐색문제를 풀었던 적이 있는데 .,,
공부하고 풀이하니 그때보다 훨씬 더 간단하게 풀 수 있어서 뿌듯했네요 ....
2차원 배열로 게임 maps가 주어지고
이를 이용해 상대팀 진영에 가장 빨리 도달하는 최단거리를 구하는 문제였습니다
maps 내부의 요소는 0, 1 (길, 벽) 중 하나로 구성되어있습니다
최단거리를 구해야했기 때문에 BFS(큐로 구현)를 이용해 풀이하였습니다. …
=> [week21] 이정민

week18/공원 산책.js, week18/모의고사.js, week18/붕대 감기.js
각 수포자가 찍는 패턴을 미리 정의하고, 정답 배열을 순회하면서 각 수포자의 점수를 계산합니다. 
점수를 기록한 배열에서 최대 점수를 찾아, 최대 점수를 얻은 수포자를 반환합니다. 
```javascript
function solution(answers) {
// 각 수포자의 찍기 패턴
const pattern1 = [1, 2, 3, 4, 5];
const pattern2 = [2, 1, 2, 3, 2, 4, 2, 5];
const pattern3 = [3, 3, 1, 1, 2, 2, 4, 4, 5, 5];
// 점수를 기록할 배열
let scores = [0, 0, 0];
// 각 수포자의 점수 계산
answers.forEach((answer, i) => {
if (answer === pattern1[i % pattern1.length]) scores[0]++;
if (answer === pattern2[i % pattern2.length]) scores[1]++;
if (answer === pattern3[i % pattern3.length]) scores[2]++;
});
// 가장 높은 점수를 찾는다
const maxScore = Math.max(...scores);
// 가장 높은 점수를 받은 사람을 배열에 담는다
let result = [];
scores.forEach((score, i) => {
if (score === maxScore) result.push(i + 1);
});
return result;
}
```
반복되는 패턴을 잘 정의하고 활용하는 것이 중요하다는 점을 배웠습니다.
공원의 …
=> [week18] Liz

week23/154540_무인도여행.js, week23/258711_도넛과막대그래프.js, week23/340213_동영상재생기.js
영상과 관련된 시간이 "mm:ss" 형식으로 주어지기 때문에
mmssToSeconds,  secondsToMmss 라는 유틸함수를 만들어서 풀이에 이용했습니다.
문제에서 요구된 커맨드에 따른 액션을 객체로 만들어서 사용했어요
prev, next, pos가 오프닝 시간이면 건너뛰어야하기때문에
skipOP을 시작할때 한번, 각 커맨드 실행후 한번씩 실행해줬습니다!!!
```javascript
/**
* "mm:ss" 형식의 문자열을 초로 변환
*
* @param {string} timeStr - "mm:ss" 형식의 시간 문자열
* @returns {number} - 총 초 단위의 시간
*/
function mmssToSeconds(timeStr) {
const [minutes, seconds] = timeStr.split(":").map(Number);
return minutes * 60 + seconds;
}
/**
* 초 단위의 시간을 "mm:ss" 형식의 문자열로 변환
*
* @param {number} seconds - 총 초 단위의 시간
* @returns {string} - "mm:ss" 형식의 문자열로 변환된 시간
*/
function secondsToMmss(seconds) {
const minutes = Math.floor(seconds / 60);
const remainingSeconds = seconds % 60;
return `${String(minutes).padStart(2, "0")}:${String(
remainingSeconds
).padStart(2, "0")}`;
} …
```
=> [week23] 이정민

week24/요격 시스템.js, week24/우박수열 정적분.js, week24/이웃한 칸.js
- 콜라츠 수열 생성: 먼저 k에서 시작하여 콜라츠 수열을 생성합니다.
- 면적 계산: 각 두 점 사이의 구간에 대해 사다리꼴 면적을 계산하고 저장합니다. 각 구간에서 면적을 계산하기 위해 사다리꼴 공식 (h1 + h2) * base / 2를 사용합니다.
- 범위 처리: 주어진 ranges 목록에서 각 범위에 대한 정적분을 계산합니다. 음수 범위는 끝에서부터 계산되므로 해당 값을 처리하고, 만약 유효하지 않은 범위가 주어지면 -1을 반환합니다.
```javascript
function solution(k, ranges) {
// k에서 시작하는 콜라츠 수열 생성
let collatz = [];
collatz.push(k);
while (k > 1) {
if (k % 2 === 0) k = k / 2;
else k = k * 3 + 1;
collatz.push(k);
}
// 각 점 사이의 면적 계산
let areas = [];
for (let i = 0; i < collatz.length - 1; i++) {
// 사다리꼴 면적 공식: (h1 + h2) * base / 2
const h1 = collatz[i];
const h2 = collatz[i + 1];
const base = 1;  // x축에서의 차이는 항상 1
const area = (h1 + h2) * base / 2;
areas.push(area);
}
// 각 범위를 처리하고 정적분 계산
let result = [];
for (const [a, b] of ranges) {
const end = areas.length + b;  // b는 …
```
=> [week24] Liz

week25/12909_올바른괄호.js, week25/17680_캐시.js, week25/17686_파일명정렬.js
```javascript
function solution(s) {
if (
s.at(0) === ")" || // 첫 번째 문자가 ')'이면 false
s.at(-1) === "(" || // 마지막 문자가 '('이면 false
(s.match(/\(/g)?.length || 0) !== (s.match(/\)/g)?.length || 0) // 여는 괄호와 닫는 괄호의 개수 비교
)
return false;
const stack = [];
for (const el of s) {
// 여는 괄호일 경우 검사없이 스택에 추가
if (el === "(") stack.push(el);
// 닫는 괄호일 경우, 검사
else {
if (stack.length === 0) return false;
stack.pop(el);
}
}
return stack.length === 0;
}
```

요구사항대로 풀이했습니다
문제가 자세히나와있어서 풀이를 깔끔하게 짜려고 노력했던것같아요 
input 제한이 있어서 유효성검사는 필요없지만 주석으로 추가해봤습니다
```javascript
/**
* 파일명을 기준으로 정렬하는 함수입니다.
*
* --------------------------------
*
* 파일명은 HEAD, NUMBER, TAIL로 구성되어 있습니다.
* 영문 대소문자, 숫자, 공백(" "), 마침표("."), 빼기 부호("-")로만 구성되어 있습니다.
* 영문자로 시작하며, 숫자를 하나 이상 포함합니다.
*  1 <= 파일명의 길이 <= 100
*
* HEAD는 문자로만 구성되어 있으며 최소 1글자를 …
```
=> [week25] 이정민
